[package]
name = "fuzz"
version = "0.0.0"
edition = "2024"
publish = false

[package.metadata]
cargo-fuzz = true

[[bin]]
bench = false
doc = false
name = "fuzz_packet_decode"
path = "fuzz_targets/fuzz_packet_decode.rs"
test = false

[[bin]]
bench = false
doc = false
name = "fuzz_handshake_decode"
path = "fuzz_targets/fuzz_handshake_decode.rs"
test = false

[dependencies]
libfuzzer-sys = "0.4"
shiguredo_srt = { path = ".." }
