[package]
name = "srt_caller"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
getrandom = "0.3"
mpeg2ts = "0.5"
noargs = "0.4"
shiguredo_mp4 = "2026.3"
shiguredo_srt = { path = "../.." }
tokio = { version = "1", features = [
  "macros",
  "net",
  "rt-multi-thread",
  "sync",
  "time",
] }
